// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AAffix: typeof import('@arco-design/web-vue')['Affix'];
    AAlert: typeof import('@arco-design/web-vue')['Alert'];
    ABreadcrumb: typeof import('@arco-design/web-vue')['Breadcrumb'];
    ABreadcrumbItem: typeof import('@arco-design/web-vue')['BreadcrumbItem'];
    AButton: typeof import('@arco-design/web-vue')['Button'];
    ACard: typeof import('@arco-design/web-vue')['Card'];
    ACascader: typeof import('@arco-design/web-vue')['Cascader'];
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox'];
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider'];
    ADatePicker: typeof import('@arco-design/web-vue')['DatePicker'];
    ADescriptions: typeof import('@arco-design/web-vue')['Descriptions'];
    ADivider: typeof import('@arco-design/web-vue')['Divider'];
    ADoption: typeof import('@arco-design/web-vue')['Doption'];
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown'];
    AEmpty: typeof import('@arco-design/web-vue')['Empty'];
    AForm: typeof import('@arco-design/web-vue')['Form'];
    AFormItem: typeof import('@arco-design/web-vue')['FormItem'];
    AGrid: typeof import('@arco-design/web-vue')['Grid'];
    AGridItem: typeof import('@arco-design/web-vue')['GridItem'];
    AIcon: typeof import('@arco-design/web-vue')['Icon'];
    AInput: typeof import('@arco-design/web-vue')['Input'];
    AInputGroup: typeof import('@arco-design/web-vue')['InputGroup'];
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber'];
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword'];
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch'];
    ALayout: typeof import('@arco-design/web-vue')['Layout'];
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent'];
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter'];
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider'];
    ALink: typeof import('@arco-design/web-vue')['Link'];
    AList: typeof import('@arco-design/web-vue')['List'];
    AListItem: typeof import('@arco-design/web-vue')['ListItem'];
    AListItemMeta: typeof import('@arco-design/web-vue')['ListItemMeta'];
    AMenu: typeof import('@arco-design/web-vue')['Menu'];
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem'];
    AMinus: typeof import('@arco-design/web-vue')['Minus'];
    AModal: typeof import('@arco-design/web-vue')['Modal'];
    AOption: typeof import('@arco-design/web-vue')['Option'];
    APagination: typeof import('@arco-design/web-vue')['Pagination'];
    AProgress: typeof import('@arco-design/web-vue')['Progress'];
    ARangePicker: typeof import('@arco-design/web-vue')['RangePicker'];
    ASelect: typeof import('@arco-design/web-vue')['Select'];
    ASpace: typeof import('@arco-design/web-vue')['Space'];
    ASpin: typeof import('@arco-design/web-vue')['Spin'];
    AStatistic: typeof import('@arco-design/web-vue')['Statistic'];
    AStep: typeof import('@arco-design/web-vue')['Step'];
    ASteps: typeof import('@arco-design/web-vue')['Steps'];
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu'];
    ASwitch: typeof import('@arco-design/web-vue')['Switch'];
    ATable: typeof import('@arco-design/web-vue')['Table'];
    ATableColumn: typeof import('@arco-design/web-vue')['TableColumn'];
    ATabPane: typeof import('@arco-design/web-vue')['TabPane'];
    ATabs: typeof import('@arco-design/web-vue')['Tabs'];
    ATag: typeof import('@arco-design/web-vue')['Tag'];
    ATextarea: typeof import('@arco-design/web-vue')['Textarea'];
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip'];
    AUpload: typeof import('@arco-design/web-vue')['Upload'];
  }
}

export {};
