export default {
  path: 'integration',
  name: 'intergration',
  component: () => import('@/views/intergration/index.vue'),
  meta: {
    // hideInMenu: true,
    ignoreCache: true,
    locale: 'navbar.intergration',
    requiresAuth: true,
    icon: 'icon-apps',
    order: 1,
  },
  children: [
    {
      path: 'content',
      name: 'allIntegration',
      component: () => import('@/views/intergration/pages/content.vue'),
      meta: {
        query: 1,
        replace: true,
        ignoreCache: true,
        locale: 'intergration.all',
        requiresAuth: true,
      },
    },
    {
      path: 'content',
      name: 'intergrationContent',
      component: () => import('@/views/intergration/pages/content.vue'),
      meta: {
        query: 2,
        replace: true,
        ignoreCache: true,
        locale: 'intergration.sourceRepo',
        requiresAuth: true,
      },
    },
    {
      path: 'content',
      name: 'containerRepo',
      component: () => import('@/views/intergration/pages/content.vue'),
      meta: {
        query: 6,
        replace: true,
        ignoreCache: true,
        locale: 'intergration.containerRepo',
        requiresAuth: true,
      },
    },
    {
      path: 'content',
      name: 'containerOrch',
      component: () => import('@/views/intergration/pages/content.vue'),
      meta: {
        query: 7,
        replace: true,
        ignoreCache: true,
        locale: 'intergration.containerOrchestration',
        requiresAuth: true,
      },
    },
    {
      path: 'content',
      name: 'proxyIntegration',
      component: () => import('@/views/intergration/pages/content.vue'),
      meta: {
        query: 3,
        replace: true,
        ignoreCache: true,
        locale: 'intergration.proxy',
        requiresAuth: true,
      },
    },
    {
      path: 'content',
      name: 'projectManage',
      component: () => import('@/views/intergration/pages/content.vue'),
      meta: {
        query: 5,
        replace: true,
        ignoreCache: true,
        locale: 'intergration.projectmanage',
        requiresAuth: true,
      },
    },
    {
      path: 'content',
      name: 'pushService',
      component: () => import('@/views/intergration/pages/content.vue'),
      meta: {
        query: 4,
        replace: true,
        ignoreCache: true,
        locale: 'intergration.pushService',
        requiresAuth: true,
      },
    },
    {
      path: 'repo-setting/:repo',
      name: 'repoConfig',
      component: () => import('@/views/intergration/pages/repo-config.vue'),
      meta: {
        hideInMenu: true,
        ignoreCache: true,
        locale: 'intergration.setting',
        requiresAuth: true,
      },
    },
    {
      path: 'proxy-setting/:repo',
      name: 'proxyConfig',
      component: () => import('@/views/intergration/pages/proxy-config.vue'),
      meta: {
        hideInMenu: true,
        ignoreCache: true,
        locale: 'intergration.setting',
        requiresAuth: true,
      },
    },
    {
      path: 'repo-proxy/:repo',
      name: 'repoPolicy',
      component: () => import('@/views/intergration/pages/repo-proxy-list.vue'),
      meta: {
        hideInMenu: true,
        ignoreCache: true,
        locale: 'intergration.setting',
        requiresAuth: true,
      },
    },
    {
      path: 'email-config',
      name: 'emailConfig',
      component: () => import('@/views/intergration/pages/email-config.vue'),
      meta: {
        hideInMenu: true,
        ignoreCache: true,
        locale: '',
        requiresAuth: true,
      },
    },
    {
      path: 'webhook',
      name: 'webhookConfig',
      component: () => import('@/views/intergration/pages/webhook-config.vue'),
      meta: {
        hideInMenu: true,
        ignoreCache: true,
        locale: '',
        requiresAuth: true,
      },
    },
    {
      path: 'container/:repo',
      name: 'standarContainer',
      component: () =>
        import('@/views/intergration/pages/container/container-config.vue'),
      meta: {
        hideInMenu: true,
        ignoreCache: true,
        locale: '',
        requiresAuth: true,
      },
    },
    {
      path: 'container-list/:repo',
      name: 'containerList',
      component: () => import('@/views/intergration/pages/container/list.vue'),
      meta: {
        hideInMenu: true,
        ignoreCache: true,
        locale: '',
        requiresAuth: true,
      },
    },
    {
      path: 'orchestrate/:repo',
      name: 'orcheContainer',
      component: () =>
        import('@/views/intergration/pages/kubernetes/kuber-config.vue'),
      meta: {
        hideInMenu: true,
        ignoreCache: true,
        locale: '',
        requiresAuth: true,
      },
    },
    {
      path: 'notifiers-list/:type',
      name: 'notifiersList',
      component: () => import('@/views/intergration/pages/webhook-list.vue'),
      meta: {
        hideInMenu: true,
        ignoreCache: true,
        locale: '',
        requiresAuth: true,
      },
    },
    {
      path: 'kubernetes-list',
      name: 'kubernetesList',
      component: () => import('@/views/intergration/pages/kubernetes/list.vue'),
      meta: {
        hideInMenu: true,
        ignoreCache: true,
        locale: '',
        requiresAuth: true,
      },
    },
    {
      path: 'project-management/:repo',
      name: 'projectManagement',
      component: () =>
        import('@/views/intergration/pages/project-management.vue'),
      meta: {
        hideInMenu: true,
        ignoreCache: true,
        locale: '',
        requiresAuth: true,
      },
    },
    {
      path: 'oauth',
      name: 'integrationAuth',
      component: () => import('@/views/intergration/pages/oauth.vue'),
      meta: {
        hideInMenu: true,
        ignoreCache: true,
        locale: '',
        requiresAuth: true,
      },
    },
  ],
};
