apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-test-
spec:
  entrypoint: main

  # This spec contains two templates: hello-hello-hello and whalesay
  templates:
  - name: main
    # Instead of just running a container
    # This template has a sequence of steps
    steps:
    - - name: hello1 # hello1 is run before the following steps
        template: run-whalesay
        arguments:
          parameters:
          - name: message
            value: "hello1"
    - - name: hello2a # double dash => run after previous step
        template: run-whalesay
        arguments:
          parameters:
          - name: message
            value: "hello2a"
      - name: hello2b # single dash => run in parallel with previous step
        template: run-whalesay
        arguments:
          parameters:
          - name: message
            value: "hello2b"

  # This is the same template as from the previous example
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
  - name: run-whalesay
    steps:
    - - name: run1 # hello1 is run before the following steps
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "run1"
    - - name: run2a # double dash => run after previous step
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "run2a"
      - name: run2b # single dash => run in parallel with previous step
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "run2b"
  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:latest
      command: [echo]
      args: ["{{inputs.parameters.message}}"]
