#!/bin/bash
set -ex

if [[ -n "${COS_REGION}" && -n "${COS_BUCKET}" ]]; then
    echo "Using base URL: https://${COS_BUCKET}.cos.${COS_REGION}.myqcloud.com/latest"
    BASE_ARGS="--base https://${COS_BUCKET}.cos.${COS_REGION}.myqcloud.com/latest"
fi

yarn build ${BASE_ARGS:-}
