name: CI

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'

env:
  NODE_VERSION: "18"

jobs:
  deps:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE_VERSION }}"
          cache: "yarn"
      - name: Deps
        run: scripts/deps
        env:
          LOCK: true
      - name: Archive Modules
        timeout-minutes: 5
        uses: actions/cache/save@v3
        with:
          key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          path: |
            ${{ github.workspace }}/node_modules

  ci-hosted:
    needs:
      - deps
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE_VERSION }}"
          cache: "yarn"
      - name: Unarchive Modules
        timeout-minutes: 5
        uses: actions/cache/restore@v3
        with:
          key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          path: |
            ${{ github.workspace }}/node_modules
      - name: Build
        run: scripts/build
        env:
          COS_BUCKET: "${{ secrets.COS_BUCKET }}"
          COS_REGION: "${{ secrets.COS_REGION }}"
      - name: Release
        uses: TencentCloud/cos-action@b0aa648235fb35a1bdd6a77f529eb0ac4c2f1c25
        if: github.event_name == 'push'
        with:
          secret_id: "${{ secrets.CI_TECENTCOS_SECRET_ID }}"
          secret_key: "${{ secrets.CI_TECENTCOS_SECRET_KEY }}"
          cos_bucket: "${{ secrets.COS_BUCKET }}"
          cos_region: "${{ secrets.COS_REGION }}"
          local_path: dist
          remote_path: latest
          accelerate: true
          clean: false

  ci-emebeded:
    needs:
      - deps
    if: github.event_name == 'push'
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: [ "latest", "${{ github.ref_name  }}" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Setup Node
        timeout-minutes: 5
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE_VERSION }}"
          cache: "yarn"
      - name: Unarchive Node Modules
        timeout-minutes: 5
        uses: actions/cache/restore@v3
        with:
          key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          path: |
            ${{ github.workspace }}/node_modules
      - name: Build
        run: scripts/build
      - name: Package
        run: scripts/package
        env:
          VERSION: "${{ matrix.version }}"
      - name: Release
        uses: TencentCloud/cos-action@b0aa648235fb35a1bdd6a77f529eb0ac4c2f1c25
        with:
          secret_id: ${{ secrets.CI_TECENTCOS_SECRET_ID }}
          secret_key: ${{ secrets.CI_TECENTCOS_SECRET_KEY }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: dist/${{ matrix.version }}.tar.gz
          remote_path: releases/${{ matrix.version }}.tar.gz
          accelerate: true
          clean: false
